import { state } from './data'

export const translations = {
  no: {
    start: 'Bildelek',
    back: 'Tilbake',
    settings: 'Innstillinger',
    abc: 'Alfabet',
    welcome: 'Velkommen',
    setup_word_amount: 'Hvor mange ord?',
    setup_categories: 'Hvilke kategorier?',
    only_new_words: 'Spill bare med nye ord',
    no_new_words: 'Fant ingen nye ord, prøv andre innstillinger',
    words: 'ord',
    setup_letters: 'Hvor mange bokstaver?',
    setup_letters_type: 'Hva vil du spille med?',
    setup_letters_casing: 'Hvilken type bokstaver?',
    setup_letters_type_all: 'Alle',
    setup_letters_type_consonants: 'Konsonanter',
    setup_letters_type_vowels: 'Vokaler',
    setup_letters_casing_uppercase: 'Store',
    setup_letters_casing_lowercase: 'Små',
    setup_letters_casing_mixed: 'Mikset',
    settings_language: 'Hvilket språk ønsker du?',
    settings_animal: 'Hvilket dyr vil du være?',
    settings_name: 'Byttet navn siden sist?',
    settings_name_placeholder: 'Hva heter barnet?',
    play_more: 'Spill igjen',
    restore: 'Kjøpt appen tidligere? Trykk her.',
    restore_success: 'Kjøp gjenskapt. Kos deg!',
    buy: 'Lås opp',
    begging_1:
      'Det å lage app tar tid, og koster penger å drifte. Du får spille 100 ord og bokstaver gratis. Men etter det må vi ta betalt. Akkurat nå har du',
    begging_2: 'ord og bokstaver igjen å lære. Lykke til!',
  },
  sv: {
    start: 'Bildlek',
    back: 'Tilbaka',
    settings: 'Inställningar',
    abc: 'Alfabetet',
    welcome: 'Välkommen',
    setup_word_amount: 'Hur många ord?',
    setup_categories: 'Vilka kategorier?',
    only_new_words: 'Spela bara med nya ord',
    no_new_words: 'Hittade inga nya ord, prova andra inställningar',
    words: 'ord',
    setup_letters: 'Hur många bokstäver?',
    setup_letters_type: 'Vad vill du spela med?',
    setup_letters_casing: 'Vilken typ av bokstäver?',
    setup_letters_type_all: 'Alla',
    setup_letters_type_consonants: 'Konsonanter',
    setup_letters_type_vowels: 'Vokaler',
    setup_letters_casing_uppercase: 'Stora',
    setup_letters_casing_lowercase: 'Små',
    setup_letters_casing_mixed: 'Mixat',
    settings_language: 'Vilket språk önskar du?',
    settings_animal: 'Vilket djur vill du vara?',
    settings_name: 'Bytt namn sedan sist?',
    settings_name_placeholder: 'Vad heter barnet?',
    play_more: 'Spela igen',
    restore: 'Har du tidigare köpt appen? Tryck här.',
    restore_success: 'Köp återskapat. Ha det så kul!',
    begging_1:
      'Det tar tid att utveckla en app, och det kostar pengar att driva. Du får spela 100 ord och bokstäver helt gratis, men efter det måste vi ta betalt. Just nu har du',
    begging_2: 'ord och bokstäver kvar att lära. Lycka till!',
    buy: 'Lås upp',
  },
  en: {
    start: 'Picture game',
    back: 'Return',
    settings: 'Settings',
    abc: 'Alphabet',
    welcome: 'Welcome',
    setup_word_amount: 'How many words?',
    setup_categories: 'Which categories?',
    only_new_words: 'Play with new words only',
    no_new_words: 'Found no new words, try again',
    words: 'words',
    setup_letters: 'How many letters?',
    setup_letters_type: 'What kind of letters?',
    setup_letters_casing: 'What casing?',
    setup_letters_type_all: 'All',
    setup_letters_type_consonants: 'Consonants',
    setup_letters_type_vowels: 'Vowels',
    setup_letters_casing_uppercase: 'Uppercase',
    setup_letters_casing_lowercase: 'Lowercase',
    setup_letters_casing_mixed: 'Mixed',
    play_more: 'Play again',
    settings_language: 'Which language?',
    settings_animal: 'What animal do you want to be?',
    settings_name: 'Changed your name lately?',
    settings_name_placeholder: 'Name of the child?',
    restore: 'Have you previously bought the app. Tap here.',
    restore_success: 'Purchase restore. Enjoy the app!',
    buy: 'Unlock',
    begging_1:
      'It takes time to develop an app, and it costs money to run it. You get to play 100 words and letters completely free, but after that we have to charge. Right now you have',
    begging_2: 'words and letters left to learn. Good luck!!',
  },
}

export type TranslationKey = keyof typeof translations['no']

export function t(key: TranslationKey) {
  return translations[state.settings?.language || 'no'][key]
}
